name: ip_tv
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_internet_speed_test: ^1.5.0
  flutter_screenutil: ^5.9.3
  flutter_speedtest: ^0.2.0
  flutter_vlc_player: ^7.4.2
  flutter_volume_controller: ^1.3.2
  get: 4.6.6
  get_cli: ^1.8.1
  get_storage: ^2.1.1
  http: ^1.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.3.0
  shimmer: ^3.0.0
  syncfusion_flutter_gauges: ^26.2.5
  url_launcher: ^6.3.0
  video_player_control_panel: ^1.1.1
  volume_control: ^0.1.5
  volume_controller: ^2.0.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

